server:
  port: 8071
spring:
  application:
    name: cloud-consumer

eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8081/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
feign:
  hystrix:
    enabled: true
