server:
  port: 9001
spring:
  application:
    name: cloud-service001
    password:
    username:
    url:
    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password:  kk031618


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
      service-url:
        defaultZone: http://localhost:8081/eureka/
      enabled: true
      healthcheck:
        enabled: true

